### ISSUE TITLE
ino_validation error(about path is invaild)

### ISSUE THREAD

**Issue by amigomcu** [ideashatch/HUB-8735#2]
hi iedeashatch,
the leastest version v4.0.3 -build20230322 and build20230428
it path "realtek/hardware/AmebaPro2/" not ideashatch ?

Traceback (most recent call last):
  File "ino_validation.py", line 56, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/home/parallels/.arduino15/packages/realtek/hardware/AmebaPro2/'
[20007] Failed to execute script 'ino_validation' due to unhandled exception!
exit status 1
Error compiling for board HUB-8735.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by amigomcu** [comment]
hi ,
could you update at linux platform (it seem modify only windows)

**Comment by H-owar-d** [comment]
hi amigomcu,
Thanks for your report, we will update linux & mac version soon.
