### ISSUE TITLE
hub-8735燒錄問題

### ISSUE THREAD

**Issue by ray910708** [ideashatch/HUB-8735#4]
![image](https://github.com/ideashatch/HUB-8735/assets/79741371/6710d919-9037-4ab8-8df9-423b92c7dbba)
報錯fail for download 0 使用ttl模組ft232rl進行燒錄

**Comment by alfredfn** [comment]
你好我遇到類似問題, 燒錄失敗, 同時出現ail for download 0和upload success, 但最後序列窗口出現 Error Invalid pin? 我以經在#5發問了

想請問你的解法與後來知到的原因 感謝

**Comment by alfredfn** [comment]
目前以知: 
1. 8735似乎很挑通訊品質
2. 上傳前必需重新按reset鍵 才能再次進入 可上傳的mode

**Comment by alfredfn** [comment]
3. 越大的檔案越難出現"upload success"
4. 就算最後出現"upload success" 程式可能也不會正常運作

**Comment by ray910708** [comment]
目前詢問官方工程師後ail for download 0的原因大機率是燒錄時供電不穩所以SPI flash進入保護模式目前解決辦法是需要寄回官方解鎖。

**Comment by alfredfn** [comment]
恩恩 有可能 我也的確看到電源燈號不穩定
謝謝你的回復  如果是這樣 我再試試有沒有直接解決的辦法 感謝

**Comment by ray910708** [comment]
不會，如果有直接解決辦法也請告訴我謝謝。
