### ISSUE TITLE
Help purchasing board from USA

### ISSUE THREAD

**Issue by bgatti** [ideashatch/HUB-8735#6]
Could you help us order the board from US address?

**Comment by ideashatch** [comment]
Hi @bgatti ,

Thanksr your interests in HUB 8735.
To avoid misunderstanding, I'm hereby to make sure your needs.
As mention, do you mean that you need international delivery to US? (FYI , the board is currently based in Taiwan)

**Comment by bgatti** [comment]
Yes,
We need purchase for delivery in the USA.

**Comment by bgatti** [comment]
We have found a way to order. Thanks.
