### ISSUE TITLE
the size of ameba_pro2_tools_linux-1.2.13.tar.gz in ieeasHatch.json is wrong

### ISSUE THREAD

**Issue by checko** [ideashatch/HUB-8735#7]
The file size is 19327398, but the value in json file is 19330076.
This causes an install error :  Error: 13 INTERNAL: Cannot install tool ideasHatch:ameba_pro2_tools@1.2.13: testing local archive integrity: testing archive size: fetched archive size differs from size specified in index: 19327398 != 19330076

**Comment by H-owar-d** [comment]
Solve in 4.0.10, Thanks for reply.
